### ISSUE TITLE
Add HDO

### ISSUE THREAD

**Issue by pernak18** [ReFRACtor/ABSCO#17]
We are now considering running ABSCO with heavy water, given interest by the TROPESS team. 

![Screen Shot 2023-01-18 at 1 16 11 PM](https://user-images.githubusercontent.com/15662679/213262063-91060b71-a9c6-433a-b667-81d3a4dc5de8.png)

Summary:
- run LNFL for water vapor, replacing the H2O spectroscopy file with the `01_h2o_162_only` (i.e., HDO lines)
- for the LBL `TAPE5`, replace H2O layer amounts with HDO amounts -- i.e., HDO goes into H2O fields

**Comment by pernak18** [comment]
@mcduffie Karen wanted me to confirm with you that HDO mixing ratios should be with respect to dry air and not water vapor. is this true? if so, we are pretty close to having HDO capability within ABSCO.

please and thanks,

**Comment by mcduffie** [comment]
HDO should be treated the same as any other species is what I am being told.

**Comment by pernak18** [comment]
should be addressed with 768c6de98b072c8c376e7e720e4e34097c173a65 and eb8129ff9ccf404a769f7bff95bbf4f060a728c2, but with caveats:
- we need to run v&v
- we're working with an HDO ASCII line file, not the full H2O one, and it has not been available in our recent public releases; the last time isotopologue line files were part of the line file releases was with [AER v3.7](https://zenodo.org/record/3837550#.Y9GP0-zMJRA)

**Comment by pernak18** [comment]
isotopologue files can be generated with some legacy IDL code at AER:

```
% setenv IDL_STARTUP ~/misc_idl/benchmark_IDL_STARTUP.pro
% idl
IDL Version 8.2.1 (linux x86_64 m64). (c) 2012, Exelis Visual Information Solutions, Inc.
Installation number: 1407-1.
Licensed for use by: Atmospheric & Environmental Research

IDL> pwd
% Compiled module: PWD.
/nas/project/rc_static/models/aer_line_parameters/AER_line_files/aer_v_3.8.1/line_files_By_Molecule/01_H2O
IDL> t7_select_lines, '01_H2O', '01_h2o_161_only', form_lnfl='F100', iso=1, mol=' 1'
% Compiled module: T7_SELECT_LINES.
% Compiled module: READ_T7_LNFL.
Writing File: 01_h2o_161_only
IDL> t7_select_lines, '01_H2O', '01_h2o_162_only', form_lnfl='F100', iso=4, mol=' 1'
Writing File: 01_h2o_162_only
IDL> t7_select_lines, '01_H2O', '01_h2o_171_only', form_lnfl='F100', iso=3, mol=' 1'
Writing File: 01_h2o_171_only
IDL> t7_select_lines, '01_H2O', '01_h2o_172_only', form_lnfl='F100', iso=6, mol=' 1'
Writing File: 01_h2o_172_only
IDL> t7_select_lines, '01_H2O', '01_h2o_181_only', form_lnfl='F100', iso=2, mol=' 1'
Writing File: 01_h2o_181_only
IDL> t7_select_lines, '01_H2O', '01_h2o_182_only', form_lnfl='F100', iso=5, mol=' 1'
Writing File: 01_h2o_182_only
```

**Comment by mcduffie** [comment]
Is this ready for testing? It is not clear what additional steps would be needed. Would we need to run the IDL script first?

**Comment by pernak18** [comment]
@mcduffie i'll work on a more complete line file package with Karen. users should not have to run the IDL script -- this was just a reminder to me in case this comes up in the future.

feel free to run with HDO as a molecule, but Karen and I still need to make time to interpret the results. that's why i kept the issue open -- verification is not complete.

apologies -- i'll branch off next time instead of pushing directly to `master`

**Comment by pernak18** [comment]
still more to do: ![slack_2023-01-27_083139](https://user-images.githubusercontent.com/15662679/215098964-ddc9a742-3b06-484e-8e75-301d2f63ec0c.png)

**Comment by pernak18** [comment]
code is good-to-go after some testing by Karen and me, merge of `hdo_dev` branch onto `master` has been [requested](https://github.com/ReFRACtor/ABSCO/pull/20).

additional, more organized documentation is or will be provided in the [Modeling HDO](https://github.com/ReFRACtor/ABSCO/wiki/Modeling-HDO) Wiki page
