### ISSUE TITLE
 list index out of range error

### ISSUE THREAD

**Issue by mcduffie** [ReFRACtor/ABSCO#9]
I ran the software to try it out. When I cam back to work it had failed with the following error:

```
TAPE5_O3_P0000.0161_T290.0K_08695-10695
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
STOP  LBLRTM EXIT 
TAPE5_O3_P0000.0161_T300.0K_08695-10695
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
STOP  LBLRTM EXIT 
TAPE5_O3_P0000.0161_T310.0K_08695-10695
STOP  ERROR - FSCGEO
TAPE5_O3_P1013.9480_T190.0K_10695-12695
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
STOP  LBLRTM EXIT 
Traceback (most recent call last):
  File "./run_LBLRTM_ABSCO.py", line 78, in <module>
    kObj.calcABSCO(mol)
  File "/home/mcduffie/Devel/refractor/absco_aer/ABSCO_compute.py", line 671, in calcABSCO
    kernel = self.degradeKern[iBand]
IndexError: list index out of range
```
Diffs for my config from the default one.

```
26,27c26,27
< wn1 =  700
< wn2 =  900
---
> wn1 =  650
> wn2 =  1150
43c43
< molnames = o3
---
> molnames = O3 CO3 H2O O2 CH4 CO2 NO2
```

**Comment by pernak18** [comment]
@mcduffie i'm not sure what happened here. your input band range is 650-1150 cm-1, but the TAPE5s listed in the standard output are in the 8695-10695 cm-1 and 10695-12695 cm-1 ranges. bands are determined by the TAPE3s that are found, and these guys have specific search strings when i do a glob. i don't think i'm out of the water yet, but please try the same run after doing a `pull` and let me know if you are still having issues
